name: publish

on:
  push:
    tags:
      - '*.*.*'

jobs:
  publish:
    name: publish
    runs-on: ubuntu-latest
    env:
      DOCKER_BUILDKIT: 1
    steps:
      - uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4
      - run: docker login -u sasaplus1 -p "${{ secrets.GITHUB_TOKEN }}" docker.pkg.github.com
      - run: docker build -t docker.pkg.github.com/${{ github.repository }}/makefile2graph:${GITHUB_REF##refs/tags/} .
      - run: docker push docker.pkg.github.com/${{ github.repository }}/makefile2graph:${GITHUB_REF##refs/tags/}
