name: test

on:
  - push
  - pull_request

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    env:
      DOCKER_BUILDKIT: 1
    steps:
      - uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4
      - run: docker build -t ${{ github.repository }} .
