name: test

on:
  - push
  - pull_request

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    env:
      DOCKER_BUILDKIT: 1
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4
      - run: docker build -t ${{ github.repository }} .
